---
version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    # open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    groups:
      "@wdio":
        patterns:
          - "@wdio/*"
          - "webdriver"
          - "webdriverio"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "21:00"
